import { useRef } from "react";
import { VideoAnalysis } from "@/types/sentinel";
import VideoPlayer from "./VideoPlayer";
import VideoPlaybackControls from "./VideoPlaybackControls";
import ChatInterface from "./ChatInterface";
import EventLogs from "./EventLogs";
import AnalyticsCharts from "./AnalyticsCharts";
import AnalysisHeader from "./AnalysisHeader";
import AIAssessmentCard from "./AIAssessmentCard";
import ThreatSummaryCards from "./ThreatSummaryCards";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { useSentinelSettings } from "@/hooks/useSentinelSettings";

interface DashboardViewProps {
  data: VideoAnalysis;
  onReset: () => void;
}

const DashboardView = ({ data, onReset }: DashboardViewProps) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const { settings } = useSentinelSettings();

  const generateReport = () => {
    if (!data.events || data.events.length === 0) {
      toast.error("No detections to report");
      return;
    }

    const reportContent = `
SURVEILLANCE ANALYSIS REPORT (AI-Powered by OpenAI)
Generated: ${new Date().toLocaleString()}
===========================================

${data.stats.overallAssessment ? `AI ASSESSMENT:\n${data.stats.overallAssessment}\n` : ""}
${data.stats.patternInsights?.length ? `\nPATTERN INSIGHTS:\n${data.stats.patternInsights.map((p, i) => `${i + 1}. ${p}`).join("\n")}\n` : ""}
VIDEO INFORMATION:
- Source: ${data.videoUrl}
- Analysis Date: ${new Date().toLocaleDateString()}

SUMMARY STATISTICS:
- Total Detections: ${data.stats.totalDetections}
- High Threat Events: ${data.stats.highThreatEvents}
- Critical Events: ${data.stats.criticalEvents || 0}
- Medium Threat Events: ${data.events.filter((e) => e.threatScore > 40 && e.threatScore <= 70).length}
- Low Threat Events: ${data.events.filter((e) => e.threatScore <= 40).length}

DETECTION LOG:
${data.events
  .map(
    (e, i) =>
      `${i + 1}. [${e.timestamp}] ${e.class.toUpperCase()} - ${e.severity || "N/A"} - Threat: ${e.threatScore}% (Confidence: ${(e.confidence * 100).toFixed(1)}%)${e.explanation ? `\n   AI: ${e.explanation}` : ""}${e.recommendedAction ? `\n   Action: ${e.recommendedAction}` : ""}`
  )
  .join("\n")}

===========================================
Report generated by SENTINEL AI System (OpenAI-powered)
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `surveillance-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Report downloaded successfully");
  };

  const setupAlertNotifications = async () => {
    try {
      const highThreatEvents = data.events.filter((e) => e.threatScore >= settings.alertThreshold);
      
      if (highThreatEvents.length === 0) {
        toast.info("No high-threat events detected in this video");
        return;
      }

      await api.sendAlert(highThreatEvents, data.videoUrl, settings.emailRecipient);
      toast.success(`Alert notifications set up for ${highThreatEvents.length} high-threat events`);
    } catch (error) {
      console.error("Alert setup error:", error);
      toast.error("Failed to set up alerts. Make sure the backend is configured.");
    }
  };

  return (
    <div className="space-y-6">
      <AnalysisHeader
        data={data}
        onReset={onReset}
        onGenerateReport={generateReport}
        onSetupAlerts={setupAlertNotifications}
      />

      <AIAssessmentCard stats={data.stats} />

      <ThreatSummaryCards events={data.events} criticalEvents={data.stats.criticalEvents} />

      <AnalyticsCharts events={data.events} />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-8 space-y-4">
          <VideoPlayer videoUrl={data.videoUrl} videoRef={videoRef} />
          <VideoPlaybackControls videoRef={videoRef} />
        </div>
        <div className="lg:col-span-4">
          <ChatInterface events={data.events} />
        </div>
        <div className="lg:col-span-12">
          <EventLogs events={data.events} />
        </div>
      </div>
    </div>
  );
};

export default DashboardView;
