import { useRef } from "react";
import { VideoAnalysis } from "@/types/sentinel";
import VideoPlayer from "./VideoPlayer";
import VideoPlaybackControls from "./VideoPlaybackControls";
import StatsCard from "./StatsCard";
import ChatInterface from "./ChatInterface";
import EventLogs from "./EventLogs";
import SystemHealth from "./SystemHealth";
import AnalyticsCharts from "./AnalyticsCharts";
import { Button } from "@/components/ui/button";
import { RotateCcw, FileText, Bell, Mail } from "lucide-react";
import { toast } from "sonner";
import axios from "axios";
import { useSentinelSettings } from "@/hooks/useSentinelSettings";

interface DashboardViewProps {
  data: VideoAnalysis;
  onReset: () => void;
}

const DashboardView = ({ data, onReset }: DashboardViewProps) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const { settings } = useSentinelSettings();

  const generateReport = () => {
    if (!data.events || data.events.length === 0) {
      toast.error("No detections to report");
      return;
    }

    const reportContent = `
SURVEILLANCE ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
===========================================

VIDEO INFORMATION:
- Source: ${data.videoUrl}
- Analysis Date: ${new Date().toLocaleDateString()}

SUMMARY STATISTICS:
- Total Detections: ${data.stats.totalDetections}
- High Threat Events: ${data.stats.highThreatEvents}
- Medium Threat Events: ${data.events.filter((e) => e.threatScore > 40 && e.threatScore <= 70).length}
- Low Threat Events: ${data.events.filter((e) => e.threatScore <= 40).length}

DETECTION LOG:
${data.events
  .map(
    (e, i) =>
      `${i + 1}. [${e.timestamp}] ${e.class.toUpperCase()} - Threat: ${e.threatScore}% (Confidence: ${(e.confidence * 100).toFixed(1)}%)`
  )
  .join("\n")}

===========================================
Report generated by SENTINEL AI System
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `surveillance-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Report downloaded successfully");
  };

  const setupAlertNotifications = async () => {
    try {
      const highThreatEvents = data.events.filter((e) => e.threatScore >= settings.alertThreshold);
      
      if (highThreatEvents.length === 0) {
        toast.info("No high-threat events detected in this video");
        return;
      }

      await axios.post("http://localhost:8000/send-alert", {
        events: highThreatEvents,
        videoUrl: data.videoUrl,
        email: settings.emailRecipient,
        sendEmail: settings.autoSendEmail,
      });

      toast.success(`Alert notifications set up for ${highThreatEvents.length} high-threat events`);
    } catch (error) {
      console.error("Alert setup error:", error);
      toast.error("Failed to set up alerts. Make sure the backend is configured.");
    }
  };

  // Show email sent indicator
  const emailSentMessage = data.emailSent ? (
    <span className="text-xs text-success flex items-center gap-1">
      <Mail className="w-3 h-3" /> Report emailed
    </span>
  ) : null;

  return (
    <div>
      {/* Header */}
      <header className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-2xl font-display font-bold text-primary">
            ANALYSIS RESULTS
          </h2>
          <div className="flex items-center gap-3 mt-1">
            <p className="text-sm text-muted-foreground">
              Video analysis complete
            </p>
            {emailSentMessage}
          </div>
        </div>
        <div className="flex items-center gap-4">
          <SystemHealth />
          <Button
            onClick={generateReport}
            variant="outline"
            size="sm"
            className="font-display"
          >
            <FileText className="w-4 h-4 mr-2" />
            REPORT
          </Button>
          <Button
            onClick={setupAlertNotifications}
            variant="outline"
            size="sm"
            className="font-display"
          >
            <Bell className="w-4 h-4 mr-2" />
            ALERTS
          </Button>
          <Button
            onClick={onReset}
            variant="outline"
            size="sm"
            className="font-display"
          >
            <RotateCcw className="w-4 h-4 mr-2" />
            NEW
          </Button>
        </div>
      </header>

      {/* Analytics Charts */}
      <AnalyticsCharts events={data.events} />

      {/* Bento Grid Dashboard */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 md:gap-6">
        {/* Main Video Feed - 8/12 width on large screens */}
        <div className="lg:col-span-8 space-y-4">
          <VideoPlayer videoUrl={data.videoUrl} videoRef={videoRef} />
          <VideoPlaybackControls videoRef={videoRef} />
        </div>

        {/* Stats Cards - 4/12 width on large screens, stacked */}
        <div className="lg:col-span-4 space-y-4 md:space-y-6">
          <StatsCard
            title="HIGH THREAT EVENTS"
            value={data.stats.highThreatEvents}
            variant="danger"
            description="Requires immediate attention"
          />
          <StatsCard
            title="TOTAL DETECTIONS"
            value={data.stats.totalDetections}
            variant="warning"
            description="Objects tracked in video"
          />
        </div>

        {/* Neural Core Chat - 4/12 width */}
        <div className="lg:col-span-4">
          <ChatInterface events={data.events} />
        </div>

        {/* Event Logs - 8/12 width */}
        <div className="lg:col-span-8">
          <EventLogs events={data.events} />
        </div>
      </div>
    </div>
  );
};

export default DashboardView;
