import { useRef } from "react";
import { VideoAnalysis } from "@/types/sentinel";
import VideoPlayer from "./VideoPlayer";
import VideoPlaybackControls from "./VideoPlaybackControls";
import StatsCard from "./StatsCard";
import ChatInterface from "./ChatInterface";
import EventLogs from "./EventLogs";
import SystemHealth from "./SystemHealth";
import AnalyticsCharts from "./AnalyticsCharts";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { RotateCcw, FileText, Bell, Mail, Shield, AlertTriangle, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { useSentinelSettings } from "@/hooks/useSentinelSettings";

interface DashboardViewProps {
  data: VideoAnalysis;
  onReset: () => void;
}

const DashboardView = ({ data, onReset }: DashboardViewProps) => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const { settings } = useSentinelSettings();

  const generateReport = () => {
    if (!data.events || data.events.length === 0) {
      toast.error("No detections to report");
      return;
    }

    const reportContent = `
SURVEILLANCE ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}
===========================================

VIDEO INFORMATION:
- Source: ${data.videoUrl}
- Analysis Date: ${new Date().toLocaleDateString()}

SUMMARY STATISTICS:
- Total Detections: ${data.stats.totalDetections}
- High Threat Events: ${data.stats.highThreatEvents}
- Medium Threat Events: ${data.events.filter((e) => e.threatScore > 40 && e.threatScore <= 70).length}
- Low Threat Events: ${data.events.filter((e) => e.threatScore <= 40).length}

DETECTION LOG:
${data.events
  .map(
    (e, i) =>
      `${i + 1}. [${e.timestamp}] ${e.class.toUpperCase()} - Threat: ${e.threatScore}% (Confidence: ${(e.confidence * 100).toFixed(1)}%)`
  )
  .join("\n")}

===========================================
Report generated by SENTINEL AI System
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `surveillance-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Report downloaded successfully");
  };

  const setupAlertNotifications = async () => {
    try {
      const highThreatEvents = data.events.filter((e) => e.threatScore >= settings.alertThreshold);
      
      if (highThreatEvents.length === 0) {
        toast.info("No high-threat events detected in this video");
        return;
      }

      await api.sendAlert(highThreatEvents, data.videoUrl, settings.emailRecipient);
      toast.success(`Alert notifications set up for ${highThreatEvents.length} high-threat events`);
    } catch (error) {
      console.error("Alert setup error:", error);
      toast.error("Failed to set up alerts. Make sure the backend is configured.");
    }
  };

  // Calculate threat levels
  const highCount = data.events.filter((e) => e.threatScore >= 70).length;
  const mediumCount = data.events.filter((e) => e.threatScore >= 40 && e.threatScore < 70).length;
  const lowCount = data.events.filter((e) => e.threatScore < 40).length;

  return (
    <div className="space-y-6">
      {/* Header with Status Bar */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="p-3 rounded-xl bg-gradient-to-br from-primary/20 to-primary/5 border border-primary/30">
            <Shield className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h2 className="text-2xl font-display font-bold text-foreground">
              ANALYSIS COMPLETE
            </h2>
            <div className="flex items-center gap-3 mt-1">
              {data.emailSent && (
                <span className="text-xs text-success flex items-center gap-1 bg-success/10 px-2 py-0.5 rounded-full">
                  <Mail className="w-3 h-3" /> Report emailed
                </span>
              )}
              <span className="text-xs text-muted-foreground font-mono">
                {data.events.length} DETECTIONS
              </span>
            </div>
          </div>
        </div>
        
        <div className="flex items-center gap-3 flex-wrap">
          <SystemHealth />
          <div className="h-6 w-px bg-border hidden md:block" />
          <Button
            onClick={generateReport}
            variant="outline"
            size="sm"
            className="font-display border-border/50 hover:border-primary/50 hover:bg-primary/5"
          >
            <FileText className="w-4 h-4 mr-2" />
            REPORT
          </Button>
          <Button
            onClick={setupAlertNotifications}
            variant="outline"
            size="sm"
            className="font-display border-border/50 hover:border-warning/50 hover:bg-warning/5"
          >
            <Bell className="w-4 h-4 mr-2" />
            ALERTS
          </Button>
          <Button
            onClick={onReset}
            variant="outline"
            size="sm"
            className="font-display border-border/50 hover:border-primary/50 hover:bg-primary/5"
          >
            <RotateCcw className="w-4 h-4 mr-2" />
            NEW
          </Button>
        </div>
      </div>

      {/* Threat Summary Cards */}
      <div className="grid grid-cols-3 gap-4">
        <Card className="p-4 bg-gradient-to-br from-destructive/10 to-transparent border-destructive/30 hover:border-destructive/50 transition-colors">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-destructive/20">
              <AlertTriangle className="w-5 h-5 text-destructive" />
            </div>
            <div>
              <p className="text-2xl font-bold font-mono text-destructive">{highCount}</p>
              <p className="text-xs text-muted-foreground uppercase tracking-wide">High Threat</p>
            </div>
          </div>
        </Card>
        <Card className="p-4 bg-gradient-to-br from-warning/10 to-transparent border-warning/30 hover:border-warning/50 transition-colors">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-warning/20">
              <Shield className="w-5 h-5 text-warning" />
            </div>
            <div>
              <p className="text-2xl font-bold font-mono text-warning">{mediumCount}</p>
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Medium Threat</p>
            </div>
          </div>
        </Card>
        <Card className="p-4 bg-gradient-to-br from-success/10 to-transparent border-success/30 hover:border-success/50 transition-colors">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-success/20">
              <CheckCircle2 className="w-5 h-5 text-success" />
            </div>
            <div>
              <p className="text-2xl font-bold font-mono text-success">{lowCount}</p>
              <p className="text-xs text-muted-foreground uppercase tracking-wide">Low Threat</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Analytics Charts */}
      <AnalyticsCharts events={data.events} />

      {/* Main Content Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Video Player Section */}
        <div className="lg:col-span-8 space-y-4">
          <VideoPlayer videoUrl={data.videoUrl} videoRef={videoRef} />
          <VideoPlaybackControls videoRef={videoRef} />
        </div>

        {/* Neural Core Chat */}
        <div className="lg:col-span-4">
          <ChatInterface events={data.events} />
        </div>

        {/* Event Logs - Full Width */}
        <div className="lg:col-span-12">
          <EventLogs events={data.events} />
        </div>
      </div>
    </div>
  );
};

export default DashboardView;