import { useState, useRef, useEffect } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Home, Video, VideoOff, AlertTriangle, FileText, Bell, Settings } from "lucide-react";
import { toast } from "sonner";
import { useAlertNotifications } from "@/hooks/useAlertNotifications";
import { useSentinelSettings } from "@/hooks/useSentinelSettings";
import RecordingControls from "@/components/sentinel/RecordingControls";
import axios from "axios";

const LiveFeed = () => {
  const [isStreaming, setIsStreaming] = useState(false);
  const [detections, setDetections] = useState<Array<{ time: string; class: string; category?: string; threat: number; confidence?: number; zone?: string; zoneId?: string; associatedObjects?: string[] }>>([]);
  const videoRef = useRef<HTMLVideoElement>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const intervalRef = useRef<NodeJS.Timeout | null>(null);
  const { requestPermission, sendAlert } = useAlertNotifications();
  const { settings } = useSentinelSettings();

  useEffect(() => {
    requestPermission();
    return () => {
      stopStream();
    };
  }, []);

  const processFrame = async () => {
    if (!videoRef.current || !canvasRef.current) return;

    const canvas = canvasRef.current;
    const video = videoRef.current;
    const ctx = canvas.getContext("2d");

    if (!ctx) return;

    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    ctx.drawImage(video, 0, 0);

    const frameData = canvas.toDataURL("image/jpeg", 0.8);

    try {
      const response = await axios.post("http://localhost:8000/process-frame", {
        frame: frameData,
      });

      if (response.data.detections && response.data.detections.length > 0) {
        const newDetections = response.data.detections;
        setDetections((prev) => [...newDetections, ...prev].slice(0, 20));

        newDetections.forEach((det: any) => {
          if (det.threat >= settings.alertThreshold) {
            sendAlert(
              `High threat detected: ${det.class} (${det.threat})`,
              "danger"
            );
          }
        });
      }
    } catch (error) {
      console.error("Error processing frame:", error);
    }
  };

  const startStream = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { width: 1280, height: 720 },
        audio: false,
      });

      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        streamRef.current = stream;
        setIsStreaming(true);
        toast.success("Live feed started - Real YOLOv8 detection active");

        // Process frames based on settings interval
        intervalRef.current = setInterval(processFrame, settings.frameProcessingInterval);
      }
    } catch (error) {
      console.error("Error accessing camera:", error);
      toast.error("Failed to access camera. Please grant camera permissions.");
    }
  };

  const stopStream = () => {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((track) => track.stop());
      streamRef.current = null;
    }
    if (videoRef.current) {
      videoRef.current.srcObject = null;
    }
    setIsStreaming(false);
    toast.info("Live feed stopped");
  };

  const generateReport = () => {
    if (detections.length === 0) {
      toast.error("No detections to report");
      return;
    }

    const reportContent = `
SURVEILLANCE REPORT - LIVE FEED
Generated: ${new Date().toLocaleString()}
===========================================

SUMMARY:
- Total Detections: ${detections.length}
- High Threat Events: ${detections.filter((d) => d.threat >= settings.alertThreshold).length}
- Medium Threat Events: ${detections.filter((d) => d.threat >= 40 && d.threat < settings.alertThreshold).length}
- Low Threat Events: ${detections.filter((d) => d.threat < 40).length}

DETECTION LOG:
${detections
  .map(
    (d, i) =>
      `${i + 1}. [${d.time}] ${d.class.toUpperCase()} - Threat: ${d.threat}% ${d.confidence ? `(Confidence: ${d.confidence}%)` : ""}`
  )
  .join("\n")}

===========================================
Report generated by SENTINEL AI System
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `live-feed-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Report downloaded");
  };

  const setupAlertNotifications = async () => {
    const highThreatEvents = detections.filter((d) => d.threat >= settings.alertThreshold);
    
    if (highThreatEvents.length === 0) {
      toast.info("No high-threat events detected yet");
      return;
    }

    try {
      await axios.post("http://localhost:8000/send-alert", {
        events: highThreatEvents.map((d, i) => ({
          id: i,
          timestamp: d.time,
          class: d.class,
          confidence: (d.confidence || 0) / 100,
          threatScore: d.threat,
        })),
        videoUrl: "live-feed",
      });

      toast.success(`Alert notifications prepared for ${highThreatEvents.length} high-threat events`);
    } catch (error) {
      console.error("Alert setup error:", error);
      toast.error("Failed to set up alerts");
    }
  };

  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-4xl font-display font-bold text-primary text-glow-primary mb-2">
              LIVE SURVEILLANCE FEED
            </h1>
            <p className="text-muted-foreground">Real-time camera monitoring with YOLOv8 detection</p>
          </div>
          <Link to="/">
            <Button variant="outline" size="sm" className="font-display">
              <Home className="w-4 h-4 mr-2" />
              HOME
            </Button>
          </Link>
          <Link to="/settings">
            <Button variant="ghost" size="sm" className="font-display">
              <Settings className="w-4 h-4 mr-2" />
              SETTINGS
            </Button>
          </Link>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Video Feed */}
          <Card className="lg:col-span-2 p-6 bg-card border-border">
            <canvas ref={canvasRef} className="hidden" />
            <div className="relative aspect-video bg-black rounded-lg overflow-hidden">
              <video
                ref={videoRef}
                autoPlay
                playsInline
                muted
                className="w-full h-full object-cover"
              />
              
              {!isStreaming && (
                <div className="absolute inset-0 flex items-center justify-center bg-black/80">
                  <div className="text-center">
                    <VideoOff className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground">Camera feed inactive</p>
                  </div>
                </div>
              )}

              {isStreaming && (
                <div className="absolute top-4 left-4">
                  <div className="flex items-center gap-2 bg-destructive/90 text-destructive-foreground px-3 py-1 rounded-full">
                    <div className="w-2 h-2 bg-white rounded-full animate-pulse" />
                    <span className="text-sm font-display">LIVE</span>
                  </div>
                </div>
              )}
            </div>

            <div className="flex gap-4 mt-4">
              {!isStreaming ? (
                <Button onClick={startStream} className="flex-1 font-display">
                  <Video className="w-4 h-4 mr-2" />
                  START FEED
                </Button>
              ) : (
                <Button
                  onClick={stopStream}
                  variant="destructive"
                  className="flex-1 font-display"
                >
                  <VideoOff className="w-4 h-4 mr-2" />
                  STOP FEED
                </Button>
              )}
              <Button
                onClick={generateReport}
                variant="outline"
                className="font-display"
                disabled={detections.length === 0}
              >
                <FileText className="w-4 h-4 mr-2" />
                REPORT
              </Button>
              <Button
                onClick={setupAlertNotifications}
                variant="outline"
                className="font-display"
                disabled={detections.length === 0}
              >
                <Bell className="w-4 h-4 mr-2" />
                ALERTS
              </Button>
            </div>

            {/* Recording Controls */}
            {isStreaming && (
              <div className="mt-4">
                <RecordingControls
                  canvasRef={canvasRef}
                  maxDuration={settings.recordingDuration}
                />
              </div>
            )}
          </Card>

          {/* Detections Log */}
          <Card className="p-6 bg-card border-border">
            <h2 className="text-xl font-display font-bold text-primary mb-4 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5" />
              LIVE DETECTIONS
            </h2>
            
            <div className="space-y-2 max-h-[500px] overflow-y-auto">
              {detections.length === 0 ? (
                <p className="text-muted-foreground text-sm">No detections yet</p>
              ) : (
                detections.map((detection, idx) => (
                  <div
                    key={idx}
                    className={`p-3 rounded-lg border ${
                      detection.threat > 70
                        ? "bg-destructive/10 border-destructive"
                        : detection.threat > 40
                        ? "bg-warning/10 border-warning"
                        : "bg-success/10 border-success"
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-display text-sm uppercase">
                        {detection.class}
                      </span>
                      <span className="text-xs text-muted-foreground font-mono">
                        {detection.time}
                      </span>
                    </div>
                    {detection.zone && (
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-[10px] text-muted-foreground">Zone</span>
                        <span className={`text-[10px] px-1.5 py-0.5 rounded ${
                          detection.zoneId === "restricted" ? "bg-destructive/20 text-destructive"
                            : detection.zoneId === "perimeter" ? "bg-warning/20 text-warning"
                            : "bg-secondary text-muted-foreground"
                        }`}>
                          {detection.zone}
                        </span>
                      </div>
                    )}
                    {detection.associatedObjects && detection.associatedObjects.length > 0 && (
                      <div className="flex items-center gap-1 mb-1 flex-wrap">
                        <span className="text-[10px] text-muted-foreground">With:</span>
                        {detection.associatedObjects.map((obj, i) => (
                          <span key={i} className="text-[10px] px-1 py-0.5 rounded bg-secondary text-foreground">{obj}</span>
                        ))}
                      </div>
                    )}
                    <div className="space-y-1">
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-muted-foreground">Threat</span>
                        <span className={`text-sm font-display font-bold ${
                          detection.threat > 70 ? "text-destructive"
                            : detection.threat > 40 ? "text-warning" : "text-success"
                        }`}>
                          {detection.threat}%
                        </span>
                      </div>
                      {detection.confidence && (
                        <div className="flex items-center justify-between">
                          <span className="text-xs text-muted-foreground">Confidence</span>
                          <span className="text-xs font-mono">{detection.confidence}%</span>
                        </div>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default LiveFeed;
