import { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Home, FileText, ArrowLeft, Calendar, Clock, AlertTriangle, 
  Download, Mail, Video, Shield, Target, Activity
} from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { AnalysisReport } from "@/types/sentinel";
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";

const ReportDetail = () => {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<AnalysisReport | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id) {
      loadReport(id);
    }
  }, [id]);

  const loadReport = async (reportId: string) => {
    try {
      const data = await api.getRecentData();
      const found = data.analyses.find((a: AnalysisReport) => a._id === reportId);
      if (found) {
        setReport(found);
      }
    } catch (error) {
      console.error("Failed to load report:", error);
      toast.error("Failed to load report");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;

    const reportContent = `
SENTINEL AI - SURVEILLANCE ANALYSIS REPORT
============================================
Video: ${report.video_filename}
Generated: ${new Date(report.created_at).toLocaleString()}
Duration: ${Math.round(report.duration_seconds || 0)} seconds

SUMMARY
-------
Total Events: ${report.total_events}
High Threat: ${report.high_threat_count}
Medium Threat: ${report.medium_threat_count}
Low Threat: ${report.low_threat_count}

DETECTION LOG
-------------
${report.events?.map((e, i) => 
  `${i + 1}. [${e.timestamp}] ${e.class?.toUpperCase()} - Confidence: ${e.confidence?.toFixed(1)}% - Threat: ${e.threatScore}%`
).join('\n') || 'No events recorded'}

============================================
Generated by Sentinel AI Surveillance System
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sentinel-report-${report._id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Report downloaded");
  };

  const handleEmailReport = async () => {
    if (!report) return;
    try {
      await api.resendReport(report._id);
      toast.success("Report sent via email");
    } catch {
      toast.error("Failed to send email");
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-muted-foreground">Loading report...</div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Card className="p-8 text-center">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <p className="text-muted-foreground mb-4">Report not found</p>
          <Link to="/reports">
            <Button>Back to Reports</Button>
          </Link>
        </Card>
      </div>
    );
  }

  const threatLevel = 
    report.high_threat_count / Math.max(report.total_events, 1) > 0.3 ? "high" :
    report.high_threat_count / Math.max(report.total_events, 1) > 0.1 ? "medium" : "low";

  const pieData = [
    { name: "High", value: report.high_threat_count, color: "hsl(var(--destructive))" },
    { name: "Medium", value: report.medium_threat_count, color: "hsl(var(--warning))" },
    { name: "Low", value: report.low_threat_count, color: "hsl(var(--success))" },
  ].filter(d => d.value > 0);

  // Create timeline data from events
  const timelineData = report.events?.slice(0, 50).map((event, index) => ({
    name: event.timestamp,
    threat: event.threatScore,
    confidence: event.confidence,
  })) || [];

  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-4">
            <Link to="/reports">
              <Button variant="outline" size="sm">
                <ArrowLeft className="w-4 h-4" />
              </Button>
            </Link>
            <div>
              <h1 className="text-3xl font-display font-bold text-primary text-glow-primary">
                ANALYSIS REPORT
              </h1>
              <p className="text-muted-foreground">{report.video_filename}</p>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={handleDownload} className="font-display">
              <Download className="w-4 h-4 mr-2" />
              DOWNLOAD
            </Button>
            <Button onClick={handleEmailReport} className="font-display">
              <Mail className="w-4 h-4 mr-2" />
              EMAIL REPORT
            </Button>
          </div>
        </div>

        {/* Report Header Card */}
        <Card className={`p-6 mb-6 bg-card border-border ${
          threatLevel === "high" ? "border-l-4 border-l-destructive glow-danger" :
          threatLevel === "medium" ? "border-l-4 border-l-warning" :
          "border-l-4 border-l-success glow-success"
        }`}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Shield className={`w-12 h-12 ${
                threatLevel === "high" ? "text-destructive" :
                threatLevel === "medium" ? "text-warning" : "text-success"
              }`} />
              <div>
                <div className="flex items-center gap-3">
                  <h2 className="text-2xl font-display font-bold">
                    {threatLevel.toUpperCase()} THREAT LEVEL
                  </h2>
                  <Badge variant={
                    threatLevel === "high" ? "destructive" :
                    threatLevel === "medium" ? "secondary" : "outline"
                  }>
                    {report.status?.toUpperCase()}
                  </Badge>
                </div>
                <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                  <span className="flex items-center gap-1">
                    <Calendar className="w-4 h-4" />
                    {new Date(report.created_at).toLocaleString()}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-4 h-4" />
                    {Math.round(report.duration_seconds || 0)}s
                  </span>
                </div>
              </div>
            </div>
            {report.video_url && (
              <a href={report.video_url} target="_blank" rel="noopener noreferrer">
                <Button variant="outline">
                  <Video className="w-4 h-4 mr-2" />
                  View Video
                </Button>
              </a>
            )}
          </div>
        </Card>

        {/* Stats Grid */}
        <div className="grid grid-cols-4 gap-4 mb-6">
          <Card className="p-6 bg-card border-border text-center">
            <Target className="w-8 h-8 text-primary mx-auto mb-2" />
            <div className="text-3xl font-display font-bold">{report.total_events}</div>
            <div className="text-sm text-muted-foreground uppercase">Total Detections</div>
          </Card>
          <Card className="p-6 bg-card border-border text-center border-l-2 border-l-destructive">
            <AlertTriangle className="w-8 h-8 text-destructive mx-auto mb-2" />
            <div className="text-3xl font-display font-bold text-destructive">{report.high_threat_count}</div>
            <div className="text-sm text-muted-foreground uppercase">High Threat</div>
          </Card>
          <Card className="p-6 bg-card border-border text-center border-l-2 border-l-warning">
            <Activity className="w-8 h-8 text-warning mx-auto mb-2" />
            <div className="text-3xl font-display font-bold text-warning">{report.medium_threat_count}</div>
            <div className="text-sm text-muted-foreground uppercase">Medium Threat</div>
          </Card>
          <Card className="p-6 bg-card border-border text-center border-l-2 border-l-success">
            <Shield className="w-8 h-8 text-success mx-auto mb-2" />
            <div className="text-3xl font-display font-bold text-success">{report.low_threat_count}</div>
            <div className="text-sm text-muted-foreground uppercase">Low Threat</div>
          </Card>
        </div>

        {/* Charts */}
        <div className="grid grid-cols-3 gap-6 mb-6">
          {/* Threat Distribution Pie */}
          <Card className="p-6 bg-card border-border">
            <h3 className="font-display font-semibold mb-4">Threat Distribution</h3>
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    dataKey="value"
                    nameKey="name"
                    cx="50%"
                    cy="50%"
                    outerRadius={70}
                    label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    labelLine={false}
                  >
                    {pieData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </Card>

          {/* Threat Timeline */}
          <Card className="col-span-2 p-6 bg-card border-border">
            <h3 className="font-display font-semibold mb-4">Threat Score Timeline</h3>
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={timelineData}>
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} />
                  <YAxis domain={[0, 100]} />
                  <Tooltip />
                  <Area
                    type="monotone"
                    dataKey="threat"
                    stroke="hsl(var(--destructive))"
                    fill="hsl(var(--destructive) / 0.3)"
                    name="Threat Score"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </div>

        {/* Events Table */}
        <Card className="p-6 bg-card border-border">
          <h3 className="font-display font-semibold mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5 text-primary" />
            Detection Events ({report.events?.length || 0})
          </h3>
          <div className="overflow-x-auto max-h-96 overflow-y-auto">
            <table className="w-full text-sm">
              <thead className="sticky top-0 bg-card">
                <tr className="border-b border-border">
                  <th className="text-left p-3 font-display">#</th>
                  <th className="text-left p-3 font-display">Timestamp</th>
                  <th className="text-left p-3 font-display">Class</th>
                  <th className="text-left p-3 font-display">Confidence</th>
                  <th className="text-left p-3 font-display">Threat Score</th>
                </tr>
              </thead>
              <tbody>
                {report.events?.map((event, index) => (
                  <tr key={index} className="border-b border-border/50 hover:bg-muted/20">
                    <td className="p-3 font-mono text-muted-foreground">{index + 1}</td>
                    <td className="p-3 font-mono">{event.timestamp}</td>
                    <td className="p-3 uppercase font-display">{event.class}</td>
                    <td className="p-3 font-mono">{event.confidence?.toFixed(1)}%</td>
                    <td className="p-3">
                      <span className={`font-display font-bold ${
                        event.threatScore >= 70 ? "text-destructive" :
                        event.threatScore >= 40 ? "text-warning" : "text-success"
                      }`}>
                        {event.threatScore}%
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>
      </div>
    </div>
  );
};

export default ReportDetail;
